# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [1]:
import pandas as pd
from numpy.array_api import trunc

csv_data = pd.read_csv('students.csv')
print(csv_data)

             Srn      Name  Marks
0  PES1UG25CA001       Ram     90
1  PES1UG25CA002      Sita     98
2  PES1UG25CA003  Lakshman     73


/var/folders/jm/hq0bsc_j09q7l0wkv9m4k3c00000gn/T/ipykernel_75367/3558147552.py:2: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  from numpy.array_api import trunc


In [2]:
batch_csv = pd.read_csv("batch.csv")
print(batch_csv)

             Srn      Name  Marks
0  PES1UG25CA001       Ram     90
1  PES1UG25CA002      Sita     98
2  PES1UG25CA003  Lakshman     73
3  PES1UG25CA004      test    100


In [3]:
read_excel = pd.read_excel("students.xlsx", sheet_name=0)
print(read_excel)

      Name  Srn
0    Radha  101
1  Krishna  102
2  Rukmani  103
3    Andal  104
4      Ram  105
5     Sita  106


In [4]:
!pip3 install sqlalchemy pymysql
# For installing the package directly at terminal

In [4]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine("mysql+pymysql://root:12345678@localhost:3306/Employee")
df = pd.read_sql("select * FROM student_scores", engine)
print(df.head())

   id   student_name  subject  score   exam_date
0   1  Alice Johnson     Math     88  2024-05-15
1   2      Bob Smith  Science     92  2024-05-15
2   3      Clara Lee  History     75  2024-05-15
3   4     Daniel Kim     Math     83  2024-05-15
4   5       Eva Chen  Science     89  2024-05-15


In [5]:
engine = create_engine("mysql+pymysql://root:12345678@localhost:3306/exam1")
df = pd.read_sql("select * FROM Employee", engine)
print(df)

   emp_id    emp_name  salary dept_id
0       1        John      20    None
1       2         Ben   20000   Sales
2       3  Alia Bhatt   30000    None
3       4     Telusko   40000    None
4       6   Antariksh   60000    None
5       8         Jai   43000    None
6       9        Asif   36000    None


In [6]:
import requests

# ingesting data from a public API (example : dummy JSON placeholder)
response = requests.get("https://jsonplaceholder.typicode.com/posts")

api_data = pd.DataFrame(response.json())
print(api_data)


    userId   id                                              title  \
0        1    1  sunt aut facere repellat provident occaecati e...   
1        1    2                                       qui est esse   
2        1    3  ea molestias quasi exercitationem repellat qui...   
3        1    4                               eum et est occaecati   
4        1    5                                 nesciunt quas odio   
..     ...  ...                                                ...   
95      10   96  quaerat velit veniam amet cupiditate aut numqu...   
96      10   97         quas fugiat ut perspiciatis vero provident   
97      10   98                        laboriosam dolor voluptates   
98      10   99  temporibus sit alias delectus eligendi possimu...   
99      10  100              at nam consequatur ea labore ea harum   

                                                 body  
0   quia et suscipit\nsuscipit recusandae consequu...  
1   est rerum tempore vitae\nsequi sint nihil r

In [7]:
# ingesting data from a public API (example : dummy JSON placeholder)
res = requests.get('https://nse.com/')
print(res.text)

<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http://gmpg.org/xfn/11">
<script type="text/javascript">
/* <![CDATA[ */
(()=>{var e={};e.g=function(){if("object"==typeof globalThis)return globalThis;try{return this||new Function("return this")()}catch(e){if("object"==typeof window)return window}}(),function({ampUrl:n,isCustomizePreview:t,isAmpDevMode:r,noampQueryVarName:o,noampQueryVarValue:s,disabledStorageKey:i,mobileUserAgents:a,regexRegex:c}){if("undefined"==typeof sessionStorage)return;const d=new RegExp(c);if(!a.some((e=>{const n=e.match(d);return!(!n||!new RegExp(n[1],n[2]).test(navigator.userAgent))||navigator.userAgent.includes(e)})))return;e.g.addEventListener("DOMContentLoaded",(()=>{const e=document.getElementById("amp-mobile-version-switcher");if(!e)return;e.hidden=!1;const n=e.querySelector("a[href]");n&&n.addEventListener("click",(()=>{sessionStorage.removeIt

In [8]:
# ingesting data from a public API (example : dummy JSON placeholder)
responsee = requests.get("https://www.google.com/?client=safari")

print(responsee.text)

<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en-IN"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="RKI_dKoU5me8d0XxN9kB2Q">(function(){var _g={kEI:'PGYfaJznOLb61e8P-dHaqQE',kEXPI:'0,202792,47,609876,2887565,669,435,448529,104244,425602,290044,11106,5230576,106,86,36812450,25340899,5088,20960,14112,22917,42255,6753,23878,7034,2105,3077,1523,328,6225,54214,9242,709,6747,8301,8206,3292,4134,30379,28334,42889,7217,2893,1212,353,7384,4397,7099,74,5796,3097,4617,5773,4311,20419,2882,3050,2,13472,3261,2990,35,6284,2804,7815,570,6146,2642,2195,201,354,656,5027,3604,923,160,10604,1460,4,4621,2731,861,1440,201,3928,1130,598,1012,2623,288,1359,117,2,1,2,2,2,3,2613,2,363,2151,1550,479,8,4,4,4272,263,300,315,69,561,3,985,483,619,624,2500,117,1466,288,1162,1912,12,59,314,158,30,173,391,623,1,259,497,979,1547,185,2,

In [9]:
# Read From System Sensor

#! pip install psutil

import psutil
battery = psutil.sensors_battery()
print("Battery Percentage: ", battery.percent)
print("Is Battery Charging: ", battery.power_plugged)
print("Battery Secends Left: ",battery.secsleft/3600)

Battery Percentage:  74
Is Battery Charging:  False
Battery Secends Left:  5.366666666666666


In [10]:
# Read From Camera

#!pip install opencv-python

import cv2
cap = cv2.VideoCapture(0) # 0 is for Default Camera
ret, frame = cap.read()
if ret:
    cv2.imwrite("Webcam_snapshot.jpg", frame)
    print("Snapshot Saved")
cap.release()

Snapshot Saved


KeyboardInterrupt: 

In [12]:
# import pandas as pd
# Batch Ingestion
import schedule
import time
def load_batch():
    df = pd.read_csv("batch.csv")
    print("Loaded today's batch")
    print(df.head())
schedule.every(1).minutes.do(load_batch)
while True:
    schedule.run_pending()
    time.sleep(1)

Loaded today's batch
             Srn      Name  Marks
0  PES1UG25CA001       Ram     90
1  PES1UG25CA002      Sita     98
2  PES1UG25CA003  Lakshman     73
3  PES1UG25CA004      test    100


KeyboardInterrupt: 

In [13]:
#!pip install yfinance

import yfinance as yf
ticker = yf.Ticker("AAPL")  ## Apple Stock Price (Stock Symbol for Apple - APPL
import time
while True:
    price = ticker.info['currentPrice']
    print("AAPLE Current Price: ", price)
    time.sleep(60)

AAPLE Current Price:  198.53
AAPLE Current Price:  198.53


KeyboardInterrupt: 

In [14]:
import requests
response = requests.get("https://www.worldometers.info/world-population/india-population/")
df = pd.read_html(response.text)[0]
print(df)

    Year  Population Yearly % Change  Yearly Change Migrants (net)  \
0   2025  1463865525           0.89%       12929734       −495,753   
1   2024  1450935791           0.89%       12866195       −630,830   
2   2023  1438069596           0.89%       12646384       −979,179   
3   2022  1425423212           0.81%       11402759     −1,353,478   
4   2020  1402617695            1.1%       14918639        −73,806   
5   2015  1328024498           1.32%       16908587       −655,085   
6   2010  1243481564           1.49%       17761048        −50,905   
7   2005  1154676322           1.77%       19350718       −929,454   
8   2000  1057922733           1.96%       19524338       −143,960   
9   1995   960301044           2.11%       19065765        −57,297   
10  1990   864972221           2.28%       18464886         125514   
11  1985   772647793           2.37%       17058754        −89,991   
12  1980   687354025           2.37%       15208898         210914   
13  1975   611309535

/var/folders/jm/hq0bsc_j09q7l0wkv9m4k3c00000gn/T/ipykernel_75367/2591976625.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(response.text)[0]


In [15]:
import numpy as np
l1 = range(1, 11)
arr1 = np.array(l1)
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11,12,13,14,15]])
type(arr)
print(arr)
print(arr1)
arr1.shape
arr.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 1  2  3  4  5  6  7  8  9 10]


(3, 5)

In [17]:
l1 = range(1,10,2)
arr = np.array(l1)
arr

array([1, 3, 5, 7, 9])

In [18]:
print(type(frame))
print(frame.shape)

<class 'numpy.ndarray'>
(1080, 1920, 3)


In [16]:
# type(frame)
# frame.shape
# arr1[4]
print(arr)
arr[1:4:1,2:4]  # Rows, Columns :- Start,Stop,step

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


array([[ 8,  9],
       [13, 14]])

In [95]:
arr2 = np.array([[3,5],[6,7],[8,9]])
print(arr2)
arr2[1:3,1]
arr2[::2]

[[3 5]
 [6 7]
 [8 9]]


array([[3, 5],
       [8, 9]])

In [21]:
import numpy as np
a1 = np.array([1,2,3,4,5,6,7,8,9])
print(a1)
print(a1[2::])

[1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]


## Simple Numpy Function / Methods

In [22]:
print(a1.argmax())  # for finding the position of max element
print(a1.max())# for finding the max element

8
9


In [23]:
print(a1.argmin())  # for finding the position of min element
print(a1.min())# for finding the min element

0
1


In [24]:
a1.ndim #Gives dimension of the array here a1 is of 1D array

1

In [25]:
a1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a1 = a1.reshape(9,1)
print(a1)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [27]:
a2 = a1.copy
a2


<function ndarray.copy>

In [28]:
## Sybsetting

In [29]:
a2[3,0] = 18
a2

TypeError: 'builtin_function_or_method' object does not support item assignment

In [ ]:
a21 = a3[copa2:copa3
      Mtrix Opesyopn]

In [30]:
# subsetting -> can be done not only for 1 dimention also from 2 dimention as well.....
a3=a1[3:]; a3

array([[4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [50]:
a1 = np.ones((3,3))
print(a1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
### Matrix operations....
a=np.array([[1,2],[3,4]])
b=np.array([[7,8],[9,10]])
print(f"a -> {a}"); print(f"b -> {b}")

a -> [[1 2]
 [3 4]]
b -> [[ 7  8]
 [ 9 10]]


In [57]:
a1 = np.eye(3,4)
print(a1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [32]:
np.add(a,b) # Adding the 2 matrix......

array([[ 8, 10],
       [12, 14]])

In [33]:
np.multiply(a, b) # Machine learning multiplication.....

array([[ 7, 16],
       [27, 40]])

In [34]:
np.divide(a, b) # Dividing the 2 matrix......

array([[0.14285714, 0.25      ],
       [0.33333333, 0.4       ]])

In [35]:
np.dot(a, b) # Human type multiplication

array([[25, 28],
       [57, 64]])

In [36]:
a.sum() # Adding all the elements in the metrix

10

In [37]:
a1.mean

<function ndarray.mean>

In [38]:
a.mean() # Calculating the mean of the array/metrix a

2.5

In [39]:
a.sum(axis=0) # summing column wise..... axis = 1 , means rows

array([4, 6])

In [40]:
# Initially all the elements will be 0, creating any dimention of array of 0's
a1=np.zeros((3, 3))

In [58]:
a1 = np.linspace(10,9)
print(a1)

[10.          9.97959184  9.95918367  9.93877551  9.91836735  9.89795918
  9.87755102  9.85714286  9.83673469  9.81632653  9.79591837  9.7755102
  9.75510204  9.73469388  9.71428571  9.69387755  9.67346939  9.65306122
  9.63265306  9.6122449   9.59183673  9.57142857  9.55102041  9.53061224
  9.51020408  9.48979592  9.46938776  9.44897959  9.42857143  9.40816327
  9.3877551   9.36734694  9.34693878  9.32653061  9.30612245  9.28571429
  9.26530612  9.24489796  9.2244898   9.20408163  9.18367347  9.16326531
  9.14285714  9.12244898  9.10204082  9.08163265  9.06122449  9.04081633
  9.02040816  9.        ]


In [59]:
a1 = np.linspace(1,9)
print(a1)

[1.         1.16326531 1.32653061 1.48979592 1.65306122 1.81632653
 1.97959184 2.14285714 2.30612245 2.46938776 2.63265306 2.79591837
 2.95918367 3.12244898 3.28571429 3.44897959 3.6122449  3.7755102
 3.93877551 4.10204082 4.26530612 4.42857143 4.59183673 4.75510204
 4.91836735 5.08163265 5.24489796 5.40816327 5.57142857 5.73469388
 5.89795918 6.06122449 6.2244898  6.3877551  6.55102041 6.71428571
 6.87755102 7.04081633 7.20408163 7.36734694 7.53061224 7.69387755
 7.85714286 8.02040816 8.18367347 8.34693878 8.51020408 8.67346939
 8.83673469 9.        ]


In [63]:
a1.reshape(1,-1)

array([[1.        , 1.16326531, 1.32653061, 1.48979592, 1.65306122,
        1.81632653, 1.97959184, 2.14285714, 2.30612245, 2.46938776,
        2.63265306, 2.79591837, 2.95918367, 3.12244898, 3.28571429,
        3.44897959, 3.6122449 , 3.7755102 , 3.93877551, 4.10204082,
        4.26530612, 4.42857143, 4.59183673, 4.75510204, 4.91836735,
        5.08163265, 5.24489796, 5.40816327, 5.57142857, 5.73469388,
        5.89795918, 6.06122449, 6.2244898 , 6.3877551 , 6.55102041,
        6.71428571, 6.87755102, 7.04081633, 7.20408163, 7.36734694,
        7.53061224, 7.69387755, 7.85714286, 8.02040816, 8.18367347,
        8.34693878, 8.51020408, 8.67346939, 8.83673469, 9.        ]])

In [65]:
a1.reshape(-1,1)

array([[1.        ],
       [1.16326531],
       [1.32653061],
       [1.48979592],
       [1.65306122],
       [1.81632653],
       [1.97959184],
       [2.14285714],
       [2.30612245],
       [2.46938776],
       [2.63265306],
       [2.79591837],
       [2.95918367],
       [3.12244898],
       [3.28571429],
       [3.44897959],
       [3.6122449 ],
       [3.7755102 ],
       [3.93877551],
       [4.10204082],
       [4.26530612],
       [4.42857143],
       [4.59183673],
       [4.75510204],
       [4.91836735],
       [5.08163265],
       [5.24489796],
       [5.40816327],
       [5.57142857],
       [5.73469388],
       [5.89795918],
       [6.06122449],
       [6.2244898 ],
       [6.3877551 ],
       [6.55102041],
       [6.71428571],
       [6.87755102],
       [7.04081633],
       [7.20408163],
       [7.36734694],
       [7.53061224],
       [7.69387755],
       [7.85714286],
       [8.02040816],
       [8.18367347],
       [8.34693878],
       [8.51020408],
       [8.673

In [67]:
a1 = np.linspace(10,9).reshape(1,-1).sum()
print(a1)

475.0


## Pandas

In [68]:
import pandas as pd

In [72]:
df = pd.read_csv("Salaries.csv")
df.head()

Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
0           1      Prof          B             19           18  Male  139750
1           2      Prof          B             20           16  Male  173200
2           3  AsstProf          B              4            3  Male   79750
3           4      Prof          B             45           39  Male  115000
4           5      Prof          B             40           41  Male  141500

In [14]:
df.ndim

2

In [73]:
df = pd.read_csv("Salaries.csv")
df.head(10)

Unnamed: 0       rank discipline  yrs.since.phd  yrs.service     sex  \
0           1       Prof          B             19           18    Male   
1           2       Prof          B             20           16    Male   
2           3   AsstProf          B              4            3    Male   
3           4       Prof          B             45           39    Male   
4           5       Prof          B             40           41    Male   
5           6  AssocProf          B              6            6    Male   
6           7       Prof          B             30           23    Male   
7           8       Prof          B             45           45    Male   
8           9       Prof          B             21           20    Male   
9          10       Prof          B             18           18  Female   

   salary  
0  139750  
1  173200  
2   79750  
3  115000  
4  141500  
5   97000  
6  175000  
7  147765  
8  119250  
9  129000

In [1]:
df.tail(15)

NameError: name 'df' is not defined

In [76]:
df.shape      #Number Of Columns, Number Of Rows

(397, 7)

In [81]:
df.columns

Index(['Unnamed: 0', 'rank', 'discipline', 'yrs.since.phd', 'yrs.service',
       'sex', 'salary'],
      dtype='object')

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Unnamed: 0     397 non-null    int64 
 1   rank           397 non-null    object
 2   discipline     397 non-null    object
 3   yrs.since.phd  397 non-null    int64 
 4   yrs.service    397 non-null    int64 
 5   sex            397 non-null    object
 6   salary         397 non-null    int64 
dtypes: int64(4), object(3)
memory usage: 21.8+ KB


In [85]:
df['rank']

0          Prof
1          Prof
2      AsstProf
3          Prof
4          Prof
         ...   
392        Prof
393        Prof
394        Prof
395        Prof
396    AsstProf
Name: rank, Length: 397, dtype: object

In [90]:
df1 = df[["rank","sex","salary"]]  # When we want the 3 columns from whole dataset

In [91]:
df1.shape

(397, 3)

In [94]:
df.iloc[:,[1,5,6]]  #Position (Go by index)

rank   sex  salary
0        Prof  Male  139750
1        Prof  Male  173200
2    AsstProf  Male   79750
3        Prof  Male  115000
4        Prof  Male  141500
..        ...   ...     ...
392      Prof  Male  103106
393      Prof  Male  150564
394      Prof  Male  101738
395      Prof  Male   95329
396  AsstProf  Male   81035

[397 rows x 3 columns]

In [95]:
df.iloc[100:151,:]      # Takes input as row as 100:151 and then column is defined after colon

Unnamed: 0       rank discipline  yrs.since.phd  yrs.service     sex  \
100         101       Prof          B             42           25    Male   
101         102       Prof          B             28           23    Male   
102         103       Prof          B             16            5    Male   
103         104       Prof          B             20           14  Female   
104         105  AssocProf          A             18           10    Male   
105         106       Prof          A             31           28    Male   
106         107  AssocProf          A             11            8    Male   
107         108  AssocProf          A             10            8    Male   
108         109  AssocProf          A             15            8    Male   
109         110       Prof          A             40           31    Male   
110         111       Prof          A             20           16    Male   
111         112  AssocProf          A             19           16    Male   
112         113   AsstProf          A              3            1    Male   
113         114       Prof          A             37           37    Male   
114         115       Prof          A             12            0  Female   
115         116       Prof          A             21            9    Male   
116         117       Prof          A             30           29    Male   
117         118       Prof          A             39           36    Male   
118         119   AsstProf          A              4            1    Male   
119         120   AsstProf          A              5            3  Female   
120         121       Prof          A             14           14    Male   
121         122       Prof          A             32           32    Male   
122         123       Prof          A             24           22    Male   
123         124  AssocProf          A             25           22  Female   
124         125       Prof          A             24           22    Male   
125         126       Prof          A             54           49    Male   
126         127       Prof          A             28           26    Male   
127         128   AsstProf          A              2            0  Female   
128         129       Prof          A             32           30    Male   
129         130   AsstProf          A              4            2    Male   
130         131  AssocProf          A             11            9    Male   
131         132       Prof          A             56           57    Male   
132         133  AssocProf          A             10            8  Female   
133         134   AsstProf          A              3            1  Female   
134         135       Prof          A             35           25    Male   
135         136       Prof          A             20           18    Male   
136         137       Prof          A             16           14    Male   
137         138       Prof          A             17           14    Male   
138         139  AssocProf          A             10            7    Male   
139         140       Prof          A             21           18    Male   
140         141  AssocProf          A             14            8    Male   
141         142  AssocProf          A             15           10    Male   
142         143       Prof          A             19           11    Male   
143         144   AsstProf          B              3            3    Male   
144         145       Prof          B             27           27    Male   
145         146       Prof          B             28           28    Male   
146         147   AsstProf          B              4            4    Male   
147         148       Prof          B             27           27    Male   
148         149       Prof          B             36           26  Female   
149         150   AsstProf          B              4            3    Male   
150         151       Prof          B             14           12    Male   



In [98]:
df.iloc[100:151,1:5:2]      # Takes input as row as 100:151 and then column 1:5 with a step of 2 is defined after colon

rank  yrs.since.phd
100       Prof             42
101       Prof             28
102       Prof             16
103       Prof             20
104  AssocProf             18
105       Prof             31
106  AssocProf             11
107  AssocProf             10
108  AssocProf             15
109       Prof             40
110       Prof             20
111  AssocProf             19
112   AsstProf              3
113       Prof             37
114       Prof             12
115       Prof             21
116       Prof             30
117       Prof             39
118   AsstProf              4
119   AsstProf              5
120       Prof             14
121       Prof             32
122       Prof             24
123  AssocProf             25
124       Prof             24
125       Prof             54
126       Prof             28
127   AsstProf              2
128       Prof             32
129   AsstProf              4
130  AssocProf             11
131       Prof             56
132  AssocProf             10
133   AsstProf              3
134       Prof             35
135       Prof             20
136       Prof             16
137       Prof             17
138  AssocProf             10
139       Prof             21
140  AssocProf             14
141  AssocProf             15
142       Prof             19
143   AsstProf              3
144       Prof             27
145       Prof             28
146   AsstProf              4
147       Prof             27
148       Prof             36
149   AsstProf              4
150       Prof             14